name: Pulumi Update
on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  update:
    name: Update
    runs-on: ubuntu-latest
    env:
      GITHUB_TOKEN: ${{ secrets.HELM_REPO_GITHUB_TOKEN }}
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version-file: aws/eks/package.json
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-region: ${{ secrets.AWS_REGION }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      - name: Setup AWS Credentials
        run: |
          mkdir ~/.aws
          echo "[default]" > ~/.aws/credentials
          echo "aws_access_key_id=${{ secrets.AWS_ACCESS_KEY_ID }}" >> ~/.aws/credentials
          echo "aws_secret_access_key=${{ secrets.AWS_SECRET_ACCESS_KEY }}" >> ~/.aws/credentials
      - uses: actions/cache@v2
        id: cache-node-modules
        with:
          path: |
            /usr/local/bin/kubectl
            '**/node_modules'
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
      - name: Install Dependencies
        if: steps.cache-node-modules.outputs.cache-hit != 'true'
        run: |
          curl -LO "https://dl.k8s.io/release/$(curl -L -s https://dl.k8s.io/release/stable.txt)/bin/linux/amd64/kubectl"
          cp kubectl /usr/local/bin/kubectl
          npm install 
      - name: Navigate to the directory
        run: cd aws/eks
      - uses: pulumi/actions@v5
        name: Pulumi Up
        with:
          command: up
          stack-name: dev
          work-dir: aws/eks
          comment-on-pr: true
          comment-on-summary: true
        env:
          PULUMI_ACCESS_TOKEN: ${{ secrets.PULUMI_ACCESS_TOKEN }}
